Sample code 부분에 대한 reorganization 제안
tldr-development/fiber-grpc pull request #17
Opened 2024-03-01 10:38 UTC by kaestro

위와 같은 형태를 사용해보면 어떨것 같다고 생각해? 네가 생각하고 있는
샘플 부분만 따로 떼어놓고 보는데 더 좋지 않을까 생각해서 한번
조정해봤어.

2024-03-03 10:03 UTC, hojin-kr commented
우선 `example` 하위로  proto, server, test 구조를 빼는 구조가 좋아보인다. 나도 이런 구조를 생각하고 만들었던게 맞는거 같아.

2024-03-03 10:06 UTC, hojin-kr commented
구조는 이렇게 가면 될것 같은데, 몇가지 확인하고 수정하고 머지되는게 좋을것 같다. 
sampletest랑 test 두개가 있는데, 이런 구조면
sampletest 는 sample로 이름 변경되고
test 하위에 sample_client.go 는 sample_server_test.go 정도의 이름이 좋지 않을까 싶어

2024-03-03 10:24 UTC, hojin-kr commented
그리고 actions 실패하는건 작업중

2024-03-03 10:25 UTC, hojin-kr requested changes
comment 작성 내용 참조

2024-03-13 08:19 UTC, closed without merging

2024-03-13 08:19 UTC, kaestro commented
reorganize 자체는 이미 호진이가 진행함. 풀리퀘를 닫고 브랜치를 삭제